import "../globals.css";
import type { Metadata } from "next";

import Navbar from "./dashboard/components/Navbar";
import Sidebar from "./dashboard/components/Sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <div className="h-full relative">
          <div className="hidden h-full md:flex md:flex-col md:fixed md:w-56 md:inset-y-0 z-[80] bg-gray-300">
            <Sidebar />
          </div>
        </div>
        <main className="md:pl-56 bg-gray-300 h-screen w-full">
          <Navbar />
          <div className="w-full h-5/6 pt-4  pr-10 pl-2">
            <div className="bg-gray-100 h-full w-full rounded-lg shadow-md">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
